parameters:
    ez_smart_cache_clear.slot.publish.class: Novactive\eZSmartCacheClearBundle\Core\Slot\Publish
    ez_smart_cache_clear.rule.parents.class: Novactive\eZSmartCacheClearBundle\Core\Rule\Parents
    ez_smart_cache_clear.rule.children.class: Novactive\eZSmartCacheClearBundle\Core\Rule\Children
    ez_smart_cache_clear.rule.subtree.class: Novactive\eZSmartCacheClearBundle\Core\Rule\Subtree
    ez_smart_cache_clear.rule.siblings.class: Novactive\eZSmartCacheClearBundle\Core\Rule\Siblings

services:
    ez_smart_cache_clear.rule.generic:
        abstract: true
        arguments:
            - "@ezplatform.http_cache.purge_client"
            - "@ezpublish.spi.persistence.cache.locationHandler"

    ez_smart_cache_clear.rule.parents:
        class: '%ez_smart_cache_clear.rule.parents.class%'
        parent: ez_smart_cache_clear.rule.generic
        tags:
            - { name: ez_smart_cache_clear.rule, ruleName: 'parents' }

    ez_smart_cache_clear.rule.children:
        class: '%ez_smart_cache_clear.rule.children.class%'
        parent: ez_smart_cache_clear.rule.generic
        tags:
            - { name: ez_smart_cache_clear.rule, ruleName: 'children' }

    ez_smart_cache_clear.rule.siblings:
        class: '%ez_smart_cache_clear.rule.siblings.class%'
        parent: ez_smart_cache_clear.rule.generic
        tags:
            - { name: ez_smart_cache_clear.rule, ruleName: 'siblings' }

    ez_smart_cache_clear.rule.subtree:
        class: '%ez_smart_cache_clear.rule.subtree.class%'
        parent: ez_smart_cache_clear.rule.generic
        tags:
            - { name: ez_smart_cache_clear.rule, ruleName: 'subtree' }

    ez_smart_cache_clear.slot.publish:
        class: '%ez_smart_cache_clear.slot.publish.class%'
        public: yes
        arguments:
            - '@ezpublish.api.persistence_handler'
            - '$config.publish;ez_smart_cache_clear$'
        tags:
            - { name: ezpublish.api.slot, signal: '*' }
            - { name: ez_smart_cache_clear.slot, signal: 'publish'}
